use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChunkInput {
    pub id: String,
    pub text: String,
    #[serde(default)]
    pub vector: Vec<f32>,
    #[serde(default)]
    pub metadata: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Calibration {
    pub slope: f32,
    pub intercept: f32,
}

impl Default for Calibration {
    fn default() -> Self {
        Self {
            slope: 1.0,
            intercept: 0.0,
        }
    }
}

impl Calibration {
    #[must_use]
    pub fn probability(&self, score: f32) -> f32 {
        let z = (self.slope * score + self.intercept).clamp(-30.0, 30.0);
        1.0 / (1.0 + (-z).exp())
    }

    /// Convert a signal-local calibrated posterior into prior-free log-likelihood
    /// evidence. `prior` must be the same corpus prior used by the final fusion.
    #[must_use]
    pub fn evidence_llr(&self, score: f32, prior: f32) -> f32 {
        logit(self.probability(score)) - logit(prior)
    }

    pub fn validate(&self, name: &str) -> anyhow::Result<()> {
        anyhow::ensure!(
            self.slope.is_finite() && self.intercept.is_finite(),
            "{name} calibration must be finite"
        );
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignalCalibrations {
    pub lexical: Calibration,
    pub vector: Calibration,
}

impl Default for SignalCalibrations {
    fn default() -> Self {
        Self {
            lexical: Calibration {
                slope: 0.5,
                intercept: -2.0,
            },
            vector: Calibration {
                slope: 8.0,
                intercept: -4.0,
            },
        }
    }
}

impl SignalCalibrations {
    fn validate(&self, prefix: &str) -> anyhow::Result<()> {
        self.lexical.validate(&format!("{prefix}.lexical"))?;
        self.vector.validate(&format!("{prefix}.vector"))?;
        Ok(())
    }
}

#[must_use]
pub fn logit(p: f32) -> f32 {
    let p = p.clamp(1e-6, 1.0 - 1e-6);
    (p / (1.0 - p)).ln()
}

#[must_use]
pub fn sigmoid(x: f32) -> f32 {
    let x = x.clamp(-30.0, 30.0);
    1.0 / (1.0 + (-x).exp())
}

/// Revision-level score contract.
///
/// Cold CAIRN scores and warm UQA scores are generated by different analyzers
/// and approximate-index implementations. They therefore MUST NOT share a raw
/// score calibration unless that equivalence has been measured. `cold` and
/// `warm` map their respective raw score domains into the same relevance
/// posterior/log-odds domain before evidence fusion.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GlobalScoringContext {
    pub base_rate: f32,
    pub bm25_k1: f32,
    pub bm25_b: f32,
    #[serde(default)]
    pub cold: SignalCalibrations,
    #[serde(default)]
    pub warm: SignalCalibrations,
    /// Reliability scaling. Values other than 1.0 are weighted log-odds fusion,
    /// not literal conditional-independence Bayes.
    pub lexical_weight: f32,
    pub vector_weight: f32,
}

impl Default for GlobalScoringContext {
    fn default() -> Self {
        Self {
            base_rate: 0.01,
            bm25_k1: 1.2,
            bm25_b: 0.75,
            cold: SignalCalibrations::default(),
            warm: SignalCalibrations::default(),
            lexical_weight: 1.0,
            vector_weight: 1.0,
        }
    }
}

impl GlobalScoringContext {
    pub fn validate(&self) -> anyhow::Result<()> {
        anyhow::ensure!(
            self.base_rate.is_finite() && self.base_rate > 0.0 && self.base_rate < 1.0,
            "base_rate must be in (0,1)"
        );
        anyhow::ensure!(
            self.bm25_k1.is_finite() && self.bm25_k1 >= 0.0,
            "bm25_k1 must be finite and non-negative"
        );
        anyhow::ensure!(
            self.bm25_b.is_finite() && (0.0..=1.0).contains(&self.bm25_b),
            "bm25_b must be in [0,1]"
        );
        self.cold.validate("cold")?;
        self.warm.validate("warm")?;
        anyhow::ensure!(
            self.lexical_weight.is_finite() && (0.0..=8.0).contains(&self.lexical_weight),
            "lexical_weight must be in [0,8]"
        );
        anyhow::ensure!(
            self.vector_weight.is_finite() && (0.0..=8.0).contains(&self.vector_weight),
            "vector_weight must be in [0,8]"
        );
        Ok(())
    }

    pub fn is_exact_single_prior(&self) -> bool {
        (self.lexical_weight - 1.0).abs() <= f32::EPSILON
            && (self.vector_weight - 1.0).abs() <= f32::EPSILON
    }
}

/// Revision-global statistics are deliberately outside immutable shards. Base
/// and delta shards can therefore be reused while every revision scores against
/// the statistics of its *live* corpus.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RevisionStats {
    pub schema_version: u32,
    pub live_document_count: u64,
    pub average_document_length: f32,
    pub term_df: BTreeMap<String, u32>,
    /// SHA-256 over the canonical, ID-sorted live corpus including text,
    /// metadata and exact f32 vector bits. Warm UQA materializations must carry
    /// the same digest before they can serve this revision.
    pub corpus_sha256: String,
    /// Identifier of the cold analyzer that produced `term_df` and shard
    /// postings.
    pub analyzer: String,
    /// Analyzer used to materialize the warm UQA database. Its raw score domain
    /// has a separate calibration from the cold analyzer.
    pub warm_analyzer: String,
    pub scoring: GlobalScoringContext,
}

impl RevisionStats {
    pub fn validate(&self) -> anyhow::Result<()> {
        anyhow::ensure!(
            self.schema_version == 3,
            "unsupported revision stats schema {} (expected 3)",
            self.schema_version
        );
        anyhow::ensure!(
            self.live_document_count > 0,
            "revision stats require at least one live document"
        );
        anyhow::ensure!(
            self.live_document_count <= u32::MAX as u64,
            "cold BM25 currently supports at most u32::MAX live documents"
        );
        anyhow::ensure!(
            self.average_document_length.is_finite() && self.average_document_length > 0.0,
            "average_document_length must be positive and finite"
        );
        anyhow::ensure!(
            self.corpus_sha256.len() == 64
                && self.corpus_sha256.bytes().all(|b| b.is_ascii_hexdigit()),
            "invalid corpus SHA-256"
        );
        anyhow::ensure!(
            !self.analyzer.is_empty() && self.analyzer.len() <= 128,
            "invalid cold analyzer identifier"
        );
        anyhow::ensure!(
            !self.warm_analyzer.is_empty() && self.warm_analyzer.len() <= 128,
            "invalid warm analyzer identifier"
        );
        for (term, df) in &self.term_df {
            anyhow::ensure!(
                !term.is_empty() && term.len() <= 4096,
                "invalid term in revision stats"
            );
            anyhow::ensure!(
                *df > 0 && *df as u64 <= self.live_document_count,
                "invalid df for term {term}"
            );
        }
        self.scoring.validate()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SearchRequest {
    pub query: String,
    #[serde(default)]
    pub query_vector: Vec<f32>,
    #[serde(default = "default_limit")]
    pub limit: usize,
    /// Retrieval pool before post-retrieval metadata filtering. If filters are
    /// selective this must be widened; neither IVF nor UQA HNSW can guarantee
    /// exact filtered top-k without a filter-aware index.
    #[serde(default = "default_candidates")]
    pub candidate_limit: usize,
    #[serde(default)]
    pub revision: Option<u64>,
    #[serde(default)]
    pub filters: BTreeMap<String, serde_json::Value>,
    /// Hard cold-path object-store budget, including revision stats and
    /// tombstones on cache misses. Prevents a pathological query from turning
    /// into unbounded range-read cost.
    #[serde(default = "default_max_remote_bytes")]
    pub max_remote_bytes: u64,
    #[serde(default = "default_max_range_reads")]
    pub max_range_reads: u64,
}

impl SearchRequest {
    #[must_use]
    pub fn effective_candidate_limit(&self) -> usize {
        self.candidate_limit.max(self.limit)
    }

    pub fn validate(&self) -> anyhow::Result<()> {
        anyhow::ensure!(
            self.limit > 0 && self.limit <= 1_000,
            "limit must be in 1..=1000"
        );
        anyhow::ensure!(
            self.candidate_limit >= self.limit && self.candidate_limit <= 100_000,
            "candidate_limit must be >= limit and <= 100000"
        );
        anyhow::ensure!(self.query.len() <= 16 * 1024, "query text too large");
        anyhow::ensure!(self.query_vector.len() <= 65_536, "query vector too large");
        anyhow::ensure!(
            self.query_vector.iter().all(|x| x.is_finite()),
            "query vector contains non-finite value"
        );
        anyhow::ensure!(self.filters.len() <= 64, "too many metadata filters");
        anyhow::ensure!(
            (1024 * 1024..=4 * 1024 * 1024 * 1024u64).contains(&self.max_remote_bytes),
            "max_remote_bytes must be in 1MiB..=4GiB"
        );
        anyhow::ensure!(
            (16..=100_000).contains(&self.max_range_reads),
            "max_range_reads must be in 16..=100000"
        );
        for (k, v) in &self.filters {
            anyhow::ensure!(
                !k.is_empty() && k.len() <= 256,
                "invalid metadata filter key"
            );
            let encoded = serde_json::to_vec(v)?;
            anyhow::ensure!(
                encoded.len() <= 64 * 1024,
                "metadata filter value too large"
            );
        }
        anyhow::ensure!(
            !self.query.trim().is_empty() || !self.query_vector.is_empty(),
            "search requires a text query, query vector, or both"
        );
        Ok(())
    }
}

fn default_limit() -> usize {
    20
}
fn default_candidates() -> usize {
    200
}
fn default_max_remote_bytes() -> u64 {
    256 * 1024 * 1024
}
fn default_max_range_reads() -> u64 {
    4096
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchHit {
    pub id: String,
    /// Revision-calibrated fused log-odds score.
    pub score: f32,
    /// sigmoid(score). It is only a calibrated probability if the supplied
    /// calibration model was validated on representative held-out labels.
    pub posterior: f32,
    pub lexical_evidence: f32,
    pub vector_evidence: f32,
    pub text: String,
    pub metadata: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchResponse {
    pub revision: u64,
    /// Immutable embedding provenance pinned by this revision.
    pub embedding_provider: String,
    pub embedding_model: String,
    pub dimension: u32,
    /// Canonical live-corpus digest from the revision statistics object.
    pub corpus_sha256: String,
    pub mode: SearchMode,
    pub score_domain: ScoreDomain,
    /// True when candidate generation is approximate or filtering is applied
    /// after a bounded candidate pool. This is intentionally explicit so API
    /// consumers do not mistake the result for an exact filtered top-k.
    pub approximate: bool,
    pub hits: Vec<SearchHit>,
    pub remote_bytes: u64,
    pub range_reads: u64,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum SearchMode {
    Cold,
    Warm,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ScoreDomain {
    /// Raw cold and warm scores use source-specific calibration models and are
    /// then fused in one revision-level log-odds domain.
    RevisionCalibratedLogOdds,
}
